name: device_frame
description: Mockups for common devices.
version: 1.4.0
homepage: https://github.com/aloisdeniel/flutter_device_preview/device_frame

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  freezed_annotation: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.0
  flutter_lints: ^1.0.4
  xml: ^6.5.0
  recase: ^4.1.0
